{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePluginDemo",
    "module": "sharkplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sharkplugin-unspecified.jar",
          "url": "sharkplugin-unspecified.jar",
          "size": 4132,
          "sha512": "cf067119013692e37ee518cdf6825033c94ed85eb7482a635893bafcc36529adfa44240f2b836ed28dc2f37ca1386f8d9d2d0a238e3455ae9fdf8a5e358b5cf4",
          "sha256": "b3b951c73119bea8ca8a0cc8eded96ed6d25dffc90b5a4af508319ffd576ab22",
          "sha1": "af688627eee644a01e6433e2518d8d6c2a2d650b",
          "md5": "8223f690b594b5432f1175fa3669b814"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sharkplugin-unspecified.jar",
          "url": "sharkplugin-unspecified.jar",
          "size": 4132,
          "sha512": "cf067119013692e37ee518cdf6825033c94ed85eb7482a635893bafcc36529adfa44240f2b836ed28dc2f37ca1386f8d9d2d0a238e3455ae9fdf8a5e358b5cf4",
          "sha256": "b3b951c73119bea8ca8a0cc8eded96ed6d25dffc90b5a4af508319ffd576ab22",
          "sha1": "af688627eee644a01e6433e2518d8d6c2a2d650b",
          "md5": "8223f690b594b5432f1175fa3669b814"
        }
      ]
    }
  ]
}
